version: '3'

dotenv: [ '.env' ]

tasks:
  yf:test:
    desc: "Login to YetiForce and fetch Contact record c2"
    vars:
      TOKEN:
        sh: ./yetiforce-ws-login.sh
    cmds:
      - echo "token={{.TOKEN}}"
      - http GET "{{.WS_URL}}/webservice/WebserviceStandard/Contacts/Record/c2" "x-token:{{.TOKEN}}"
